# Docker Compose configuration for Ryzer Tokenized Assets
# This sets up the entire stack: frontend, backend, and database
# 
# Usage:
#   docker-compose up        - Start all services
#   docker-compose down      - Stop all services
#   docker-compose logs -f   - View logs

# Simplified Docker Compose for Local Development
# Usage: docker-compose up

version: '3.8'

services:
  # Next.js Frontend Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ryzer-tokenized-assets
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
